In [0]:
from array import array

In [0]:
my_arr = array("i",[1,-2,3,4,5])
print(my_arr)
print(type(my_arr))

array('i', [1, -2, 3, 4, 5])
<class 'array.array'>


In [0]:
for index in range(len(my_arr)):
    print(my_arr[index], end = " ")  

1 -2 3 4 5 

In [0]:
my_arr.insert(0,100)

In [0]:
my_arr

array('i', [100, 1, -2, 3, 4, 5])

In [0]:
my_arr.index(-2)

2

In [0]:
my_arr.append(7)

In [0]:
my_arr

array('i', [100, 1, -2, 3, 4, 5, 7])

In [0]:
my_arr[:4]

array('i', [100, 1, -2, 3])

In [0]:
my_arr.remove(100)

In [0]:
my_arr

array('i', [1, -2, 3, 4, 5, 7])

In [0]:
my_arr.pop()

7

In [0]:
my_arr.pop(1)

-2

In [0]:
my_arr

array('i', [1, 3, 4, 5])

In [0]:
my_arr[2]

4

In [0]:
my_arr[2] = 24

In [0]:
my_arr

array('i', [1, 3, 24, 5])

In [0]:
import numpy as np

In [0]:
my_arr2 = np.array([1,2,3,4,5])

In [0]:
my_arr2

array([1, 2, 3, 4, 5])

In [0]:
type(my_arr2)

numpy.ndarray

In [0]:
my_arr2.ndim

1

In [0]:
my_arr2[2]

3

In [0]:
my_arr3 = np.array(
    [[1,2,3,4,5],
    [6,7,8,9,10]]
)

In [0]:
my_arr3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [0]:
my_arr3.ndim

2

In [0]:
my_arr3[0][1]

2

In [0]:
my_arr3[0][4]

5

In [0]:
my_arr3[1][3]

9

In [0]:
thr_arr = np.array(
    [
     [[1,2,3],[10,20,30],[100,200,300]],
     [[4,5,6],[40,50,60],[400,500,600]],
     [[7,8,9],[70,80,90],[700,800,900]]
    ], dtype=float
)

In [0]:
thr_arr.ndim

3

In [0]:
thr_arr.shape

(3, 3, 3)

In [0]:
thr_arr

array([[[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]],

       [[  4.,   5.,   6.],
        [ 40.,  50.,  60.],
        [400., 500., 600.]],

       [[  7.,   8.,   9.],
        [ 70.,  80.,  90.],
        [700., 800., 900.]]])

In [0]:
thr_arr[0][1][0]

10.0

In [0]:
a = np.array([1,2,3,4,5], dtype=int)

In [0]:
a

array([1, 2, 3, 4, 5])

In [0]:
a.ndim

1

In [0]:
sev = np.full((2,3,3),7)

In [0]:
sev

array([[[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]]])

In [0]:
z = np.zeros((3,3))

In [0]:
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [0]:
o = np.ones([5,5])

In [0]:
o

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [0]:
np.ones([1,2],dtype=int)

array([[1, 1]])

In [0]:
e = np.empty([2,2])

In [0]:
e

array([[5.e-324, 5.e-324],
       [5.e-324, 0.e+000]])

In [0]:
r = np.random.random([3,4])

In [0]:
r

array([[0.27981   , 0.2913664 , 0.32091166, 0.03108961],
       [0.82736791, 0.49376461, 0.61627056, 0.89435035],
       [0.08477061, 0.78359368, 0.73966895, 0.88818102]])

In [0]:
ar = np.arange(105,501,5)

In [0]:
ar

array([105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160, 165,
       170, 175, 180, 185, 190, 195, 200, 205, 210, 215, 220, 225, 230,
       235, 240, 245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295,
       300, 305, 310, 315, 320, 325, 330, 335, 340, 345, 350, 355, 360,
       365, 370, 375, 380, 385, 390, 395, 400, 405, 410, 415, 420, 425,
       430, 435, 440, 445, 450, 455, 460, 465, 470, 475, 480, 485, 490,
       495, 500])

In [0]:
l = np.linspace(10,100)

In [0]:
l

array([ 10.        ,  11.83673469,  13.67346939,  15.51020408,
        17.34693878,  19.18367347,  21.02040816,  22.85714286,
        24.69387755,  26.53061224,  28.36734694,  30.20408163,
        32.04081633,  33.87755102,  35.71428571,  37.55102041,
        39.3877551 ,  41.2244898 ,  43.06122449,  44.89795918,
        46.73469388,  48.57142857,  50.40816327,  52.24489796,
        54.08163265,  55.91836735,  57.75510204,  59.59183673,
        61.42857143,  63.26530612,  65.10204082,  66.93877551,
        68.7755102 ,  70.6122449 ,  72.44897959,  74.28571429,
        76.12244898,  77.95918367,  79.79591837,  81.63265306,
        83.46938776,  85.30612245,  87.14285714,  88.97959184,
        90.81632653,  92.65306122,  94.48979592,  96.32653061,
        98.16326531, 100.        ])

In [0]:
l[1]-l[0]

1.8367346938775508

In [0]:
l[2]-l[1]

1.8367346938775508

In [0]:
l[7]-l[6]

1.836734693877549

In [0]:
l2 = np.linspace(0,100)

In [0]:
l2

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [0]:
l3 = np.linspace(0,100,10)

In [0]:
l3

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [0]:
np.linspace(11,20,10,dtype=int)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [0]:
l3.size

10

In [0]:
l3.dtype

dtype('float64')

In [0]:
thr_arr.size

27

In [0]:
l3.sum()

500.0

In [0]:
l3.min()

0.0

In [0]:
l3.max()

100.0

In [0]:
l3.mean()

50.0

In [0]:
np.median(l3)

50.0

In [0]:
np.std(l3)

31.91423692521127

In [0]:
a

array([1, 2, 3, 4, 5])

In [0]:
b = np.array([4,5,6,7,8])

In [0]:
a + b

array([ 5,  7,  9, 11, 13])

In [0]:
c = np.array([1,2,3])

In [0]:
a - b

array([-3, -3, -3, -3, -3])

In [0]:
a * 2

array([ 2,  4,  6,  8, 10])

In [0]:
a / 2

array([0.5, 1. , 1.5, 2. , 2.5])

In [0]:
a // 2

array([0, 1, 1, 2, 2])

In [0]:
a * b

array([ 4, 10, 18, 28, 40])

In [0]:
a / b

array([0.25      , 0.4       , 0.5       , 0.57142857, 0.625     ])

In [0]:
a

array([1, 2, 3, 4, 5])

In [0]:
np.exp(a)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [0]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [0]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [0]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

In [0]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [0]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [0]:
a[0] 

1

In [0]:
a[0] = 10

In [0]:
a

array([10,  2,  3,  4,  5])

In [0]:
b = np.array([1,2,3,4,5,6])

In [0]:
b.shape

(6,)

In [0]:
b = b.reshape(2,3)

In [0]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
o = b.flatten()

In [0]:
o.ndim

1

In [0]:
o

array([1, 2, 3, 4, 5, 6])

In [0]:
r = b.ravel()

In [0]:
r

array([1, 2, 3, 4, 5, 6])

In [0]:
t = b.transpose()

In [0]:
t

array([[1, 4],
       [2, 5],
       [3, 6]])

In [0]:
s = b.swapaxes(0,1)

In [0]:
s

array([[1, 4],
       [2, 5],
       [3, 6]])

In [0]:
b = np.array([1,2,3,4]).reshape(2,2)

In [0]:
i = np.linalg.inv(b)

In [0]:
i

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [0]:
a = np.array([20,30,10,40])

In [0]:
b = b.ravel()

In [0]:
j = np.concatenate((a,b))
j

array([20, 30, 10, 40,  1,  2,  3,  4])

In [0]:
st = np.stack((a,b))
st

array([[20, 30, 10, 40],
       [ 1,  2,  3,  4]])

In [0]:
hs = np.hstack((a,b))
hs

array([20, 30, 10, 40,  1,  2,  3,  4])

In [0]:
vs = np.vstack((a,b))
vs

array([[20, 30, 10, 40],
       [ 1,  2,  3,  4]])

In [0]:
svs = np.split(vs,2)
svs

[array([[20, 30, 10, 40]]), array([[1, 2, 3, 4]])]

In [0]:
hvs = np.split(hs,2)
hvs

[array([20, 30, 10, 40]), array([1, 2, 3, 4])]

In [0]:
odd = np.array([1,2,3,4,5])
sodd = np.split(odd,2)

In [0]:
hsvs = np.hsplit(vs,2)
hsvs

[array([[20, 30],
        [ 1,  2]]), array([[10, 40],
        [ 3,  4]])]

In [0]:
hsvs[0]

array([[20, 30],
       [ 1,  2]])

In [0]:
vsvs = np.vsplit(vs,2)
vsvs

[array([[20, 30, 10, 40]]), array([[1, 2, 3, 4]])]

In [0]:
dvs =  np.delete(vs,0)

In [0]:
vs

array([[20, 30, 10, 40],
       [ 1,  2,  3,  4]])

In [0]:
dvs

array([30, 10, 40,  1,  2,  3,  4])

In [0]:
dvs =  np.delete(vs,2)

In [0]:
dvs

array([20, 30, 40,  1,  2,  3,  4])

In [0]:
hsvs[0]

array([[20, 30],
       [ 1,  2]])

In [0]:
dhsvs = np.delete(hsvs[0],0,1)

In [0]:
dhsvs

array([[30],
       [ 2]])

In [0]:
ihsvs = np.insert(hsvs[0],4,500)

In [0]:
ihsvs

array([ 20,  30,   1,   2, 500])

In [0]:
dhsvs = np.delete(hsvs[0],2)
dhsvs

array([20, 30,  2])

In [0]:
a

array([20, 30, 10, 40])

In [0]:
ra = np.resize(a,(2,3))
ra

array([[20, 30, 10],
       [40, 20, 30]])

In [0]:
aa = np.append(a,[10,20])

In [0]:
aa

array([20, 30, 10, 40, 10, 20])

In [0]:
np.savetxt()
np.loadtxt()